image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install -y tzdata zip unzip software-properties-common
  - LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
  - apt-get -y update
  - apt-get -y upgrade
  - apt-get install -y php7.1 php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-mysql php7.1-mbstring php7.1-mcrypt php7.1-zip php7.1-fpm
  - service php7.1-fpm start
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

install:
  script:
    - php composer.phar install

stage_deploy:
  artifacts:
    paths:
      - build/
  only:
    - provisioning
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - ssh -p22 $SERVER_USER@$SERVER_HOST "mkdir -p /var/www/html"
    - ssh -p22 $SERVER_USER@$SERVER_HOST "mkdir -p /var/www/html_tmp"
    - scp -P22 -r build/* $SERVER_USER@$SERVER_HOST:/var/www/html_tmp"
    - ssh -p22 $SERVER_USER@$SERVER_HOST "mv /var/www/html /var/www/html_old && mv /var/www/html_tmp /var/www/html"
    - ssh -p22 $SERVER_USER@$SERVER_HOST "rm -rf /var/www/html_old"